import Head from 'next/head'
import Card from "@/components/Card";
import process from "next/dist/build/webpack/loaders/resolve-url-loader/lib/postcss";

// указываем сервер, чтобы при локальной разработке не было ошибки при запросе в getInitialProps
const server = process.env.NODE_ENV === 'production' ? 'https://mysite.com' : 'http://localhost:3000'

export default function Home({ movies }) {
  return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section>
          <h1>Киноафиша</h1>
          <p>
            Киноафиша – это наиболее полная информация о кино и кинотеатрах.
            <br />
            У нас вы найдёте подробные сведения о фильмах, новостях мира кино и кинозвёзд
          </p>
          <div className="movies">
            { movies.map(movie =>
                    <Card key={movie.title} url={movie.url} title={movie.title} rating={movie.rating} />)
            }
          </div>
        </section>
      </>
  )
}

Home.getInitialProps = async () => {
  const response = await fetch(server + '/db/movies.json');
  const data = await response.json();

  console.log(data)

  return {
      movies: data
  }
}
